plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '5.1.+'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id "org.spongepowered.mixin" version "0.7-SNAPSHOT"
}

version = '1.0'
group = 'com.prosbloom'
archivesBaseName = 'cerestech'

// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    //mappings channel: 'official', version: '1.20.1'
    mappings channel: "parchment", version: "2023.09.03-1.20.1"
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'cerestech'

            mods {
                cerestech {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'cerestech'
            mods {
                cerestech{
                    source sourceSets.main
                }
            }
        }
        gameTestServer {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'cerestech'
            mods {
                cerestech{
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', 'cerestech', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            mods {
                cerestech {
                    source sourceSets.main
                }
            }
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }





repositories {
    jcenter()
    flatDir {
        dirs "libs"
    }
    maven {
        url = "https://maven.minecraftforge.net/"
    }
    maven {
        url = "https://repo.spongepowered.org/maven"
    }
    maven {
        url = "https://maven.blamejared.com/"
        content {
            includeGroup "mezz.jei"
            includeGroup "com.blamejared.crafttweaker"
            includeGroup "vazkii.patchouli"
        }
    }
    maven {
        url = "https://maven.architectury.dev/"
        content {
            includeGroup "dev.architectury"
        }
    }
    maven {
        url = "https://maven.saps.dev/releases/"
        content {
            includeGroup "dev.latvian.mods"
        }
    }
    maven {
        url = "https://maven.tterrag.com/"
        content {
            includeGroup "com.tterrag.registrate"
            includeGroup "com.simibubi.create"
            includeGroup "com.jozufozu.flywheel"
        }
    }
    maven {
        url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
        content {
            includeGroup "software.bernie.geckolib"
        }
    }
    maven {
        url = "https://maven.covers1624.net/"
        content {
            includeGroup "com.teamcofh"
        }
    }
    maven {
        url = "https://maven.firstdarkdev.xyz/snapshots/"
        content {
            includeGroup "com.lowdragmc.ldlib"
        }
    }
    maven {
        name = 'GTCEu Maven'
        url = 'https://maven.gtceu.com'
        content {
            includeGroup 'com.gregtechceu.gtceu'
        }
    }
    maven {
        url = "https://cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://modmaven.dev/"
    }
    maven {
        url = 'https://maven.nova-committee.cn/releases'
    }
}
dependencies {
    minecraft "net.minecraftforge:forge:1.20.1-47.3.12"
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    implementation fg.deobf("mezz.jei:jei-1.20.1-forge:15.20.0.105")
    implementation fg.deobf("com.lowdragmc.ldlib:ldlib-forge-1.20.1:1.0.33.b") { transitive = false }
    implementation fg.deobf("com.gregtechceu.gtceu:gtceu-1.20.1:1.6.3") { transitive = false }
    //implementation fg.deobf("com.simibubi.create:create-1.20.1:0.5.1.d-9:all") { transitive = false }
    //implementation fg.deobf("com.jozufozu.flywheel:Flywheel-Forge-1.20.1:0.6.9-5") { transitive = false }

    implementation fg.deobf("curse.maven:configuration-444699:4608425") {transitive = false}

    implementation fg.deobf("curse.maven:applied-energistics-223794:5989151") {transitive = false}
    implementation fg.deobf("curse.maven:avaritia-reforged-623969:5114105") {transitive = false}
    implementation fg.deobf("curse.maven:codechicken-lib-1-8-242818:5753868")
    implementation fg.deobf("curse.maven:brandons-core-231382:5422013")
    implementation fg.deobf("curse.maven:draconic-evolution-223565:6065044") {transitive = false}

    compileOnly fg.deobf("com.tterrag.registrate:Registrate:MC1.20-1.3.11")
    //jarJar(group: 'com.tterrag.registrate', name: 'Registrate', version: "[MC1.20)")


    implementation fg.deobf("curse.maven:top-245211:5159287") {transitive = false}
}


mixin {
    add sourceSets.main, "cerestech.refmap.json"
    config "ct-common.mixins.json"
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "cerestech",
                "Specification-Vendor"    : "cerestechareus",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "cerestechsareus",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : "ct-common.mixins.json"
        ])
    }
}

jarJar.enable()
reobf {
    jarJar {}
}
jar.finalizedBy('reobfJar')

processResources {
    duplicatesStrategy='include'
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
